
package pkg651puntodeventa;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;


public class Ventas extends javax.swing.JFrame {
    String productos [] ={"maruchan","cigarros","cafe","galletas"};
    double precios [] ={25.00,75.00,20.00,16.00};
    
    double precio=0;
    int cantidad=0;
   
        
    //modelo combox
    DefaultComboBoxModel comboModel = new DefaultComboBoxModel(productos);
   
    ArrayList<ventas1>listaDeVentas= new ArrayList<ventas1>();
    DefaultTableModel tableModel= new DefaultTableModel();
    
    public Ventas() {
        initComponents();
        this.setTitle("Punto De Venta La Mera");//titulo 
        this.setLocationRelativeTo(null);
        
        tableModel.addColumn("descripcion");
        tableModel.addColumn("precio");
        tableModel.addColumn("cantidad");
        tableModel.addColumn("importe");
        Cboproductos.setModel(comboModel);//verlo
        
        actualizar();
        calcularPrecios();
    
        
    }
    public boolean buscar(ventas1 nueva){
        for (ventas1 v:listaDeVentas){
            if(v.getID()==nueva.getID()){
                int nuevacantidad=v.getCantidad()+nueva.getCantidad();
                v.setCantidad(nuevacantidad);
                v.setImporte(v.getPrecio()*nuevacantidad);
                return true;
        }
            
    }
        return false;
        }
    
    
    public void actualizar(){
        Tblproductos.setModel(tableModel);
        while(tableModel.getRowCount()>0){
        tableModel.removeRow(0);
        }
        double subtotal=0;
        for (ventas1 v:listaDeVentas){
            Object x[]= new Object[4];
            x[0]= v.getDescripcion();
            x[1]=v.getPrecio();
            x[2]=v.getCantidad();
            x[3]=v.getImporte();
            subtotal+=v.getImporte();
            tableModel.addRow(x);
            
        }
        double iva=subtotal*0.16;
        double total=subtotal+iva;
        Lblsubtotal.setText(String.valueOf(subtotal));
        Lbliva.setText(String.valueOf(iva));
        Lbltotal.setText(String.valueOf(total));
    
     }
    
        public void calcularPrecios(){ //calcular precio y importe
            precio = precios[Cboproductos.getSelectedIndex()];
            cantidad = Integer.parseInt(Spncantidad.getValue().toString());
            Lblprecio.setText(String.valueOf(precio));
            Lblimporte.setText(String.valueOf(precio*cantidad));
        }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lblproducto = new javax.swing.JLabel();
        Lblcantidad = new javax.swing.JLabel();
        Cboproductos = new javax.swing.JComboBox<>();
        Spncantidad = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lblprecio = new javax.swing.JLabel();
        Lblimporte = new javax.swing.JLabel();
        Btnagregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tblproductos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Lblsubtotal = new javax.swing.JLabel();
        Lbliva = new javax.swing.JLabel();
        Lbltotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lblproducto.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Lblproducto.setForeground(new java.awt.Color(153, 0, 204));
        Lblproducto.setText("Producto:");

        Lblcantidad.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Lblcantidad.setForeground(new java.awt.Color(153, 0, 153));
        Lblcantidad.setText("Cantidad:");

        Cboproductos.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        Cboproductos.setForeground(new java.awt.Color(204, 153, 255));
        Cboproductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cboproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboproductosActionPerformed(evt);
            }
        });

        Spncantidad.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        Spncantidad.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        Spncantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpncantidadStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Precio:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Importe");

        Lblprecio.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Lblprecio.setForeground(new java.awt.Color(204, 51, 255));
        Lblprecio.setText("0.0Mx");

        Lblimporte.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Lblimporte.setForeground(new java.awt.Color(204, 0, 255));
        Lblimporte.setText("0.0Mx");

        Btnagregar.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Btnagregar.setForeground(new java.awt.Color(153, 0, 153));
        Btnagregar.setText("+");
        Btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnagregarActionPerformed(evt);
            }
        });

        Tblproductos.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        Tblproductos.setForeground(new java.awt.Color(153, 0, 153));
        Tblproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tblproductos);

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 153));
        jLabel7.setText("IVA:");

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("Total:");

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Subtotal:");

        Lblsubtotal.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Lblsubtotal.setForeground(new java.awt.Color(204, 0, 255));
        Lblsubtotal.setText("0.0Mx");

        Lbliva.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Lbliva.setForeground(new java.awt.Color(204, 0, 255));
        Lbliva.setText("0.0Mx");

        Lbltotal.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        Lbltotal.setForeground(new java.awt.Color(204, 0, 255));
        Lbltotal.setText("0.0Mx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbltotal)
                    .addComponent(Lbliva)
                    .addComponent(Lblsubtotal))
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lblproducto)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cboproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Spncantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Lblcantidad))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lblimporte)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lblprecio)
                                .addGap(39, 39, 39)
                                .addComponent(Btnagregar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lblprecio)
                            .addComponent(Cboproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lblproducto)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Btnagregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lblcantidad)
                    .addComponent(Spncantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Lblimporte))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Lblsubtotal))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(Lbliva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Lbltotal))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CboproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboproductosActionPerformed
        // TODO add your handling code here:
        calcularPrecios();
    
    }//GEN-LAST:event_CboproductosActionPerformed

    private void SpncantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpncantidadStateChanged
        // TODO add your handling code here:
        calcularPrecios();
       
    }//GEN-LAST:event_SpncantidadStateChanged

    private void BtnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnagregarActionPerformed
        // TODO add your handling code here:
        ventas1 ventas1 = new ventas1();
        
        ventas1.setID(Cboproductos.getSelectedIndex());
        ventas1.setDescripcion(Cboproductos.getSelectedItem().toString());
        ventas1.setPrecio(precio);
        ventas1.setCantidad(cantidad);
        ventas1.setImporte(precio*cantidad);
        if(!buscar(ventas1)){
        listaDeVentas.add(ventas1);  
        }
        
        actualizar();
        
    }//GEN-LAST:event_BtnagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnagregar;
    private javax.swing.JComboBox<String> Cboproductos;
    private javax.swing.JLabel Lblcantidad;
    private javax.swing.JLabel Lblimporte;
    private javax.swing.JLabel Lbliva;
    private javax.swing.JLabel Lblprecio;
    private javax.swing.JLabel Lblproducto;
    private javax.swing.JLabel Lblsubtotal;
    private javax.swing.JLabel Lbltotal;
    private javax.swing.JSpinner Spncantidad;
    private javax.swing.JTable Tblproductos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
